CoreProje/Controllers/ExperienceController.cs
using BussinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace CoreProje.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());
        public IActionResult Index()
        {
            ViewBag.v1 = "Deneyim Listesi";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Listesi";
            var values = experienceManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddExperience()
        {
            ViewBag.v1 = "Deneyim Ekle";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Ekle";
            return View();
        }
        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteExperience(int id)
        {
            var values = experienceManager.TGetByID(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditExperience(int id)
        {
            ViewBag.v1 = "Deneyim Güncelle";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Güncelle";
            var values = experienceManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

CoreProje/Views/Experience/AddExperience.cshtml
@model EntityLayer.Concrete.Experience

@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
{
    <br />
    @Html.Label("Deneyim Başlığı")
    @Html.TextBoxFor(x=>x.Name, new {@class = "form-control text-white"})
        <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x=>x.Date, new {@class = "form-control text-white"})
        <br />
          @Html.Label("Image Url")
    @Html.TextBoxFor(x=>x.ImageUrl, new {@class = "form-control text-white"})
        <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x=>x.Description,10,3, new {@class = "form-control text-white"})
    <br />
        <button class="btn btn-success">Kaydet</button>
}

CoreProje/Views/Experience/EditExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "EditExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
<div class="container">

    @using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
    {
        @Html.HiddenFor(x=>x.ExperienceID)
        <br />
        @Html.Label("Deneyim Başlığı")
        @Html.TextBoxFor(x=>x.Name, new {@class = "form-control"})
        <br />
        @Html.Label("Tarih")
        @Html.TextBoxFor(x=>x.Date, new {@class = "form-control"})
        <br />
        @Html.Label("Image Url")
        @Html.TextBoxFor(x=>x.ImageUrl, new {@class = "form-control"})
        <br />
        @Html.Label("Açıklama")
        @Html.TextAreaFor(x=>x.Description,10,3, new {@class = "form-control"})
        <br />
        <button class="btn btn-success">Güncelle</button>
    }
</div>

CoreProje/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
<div class="grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" class="sort">#</th>
                            <th scope="col" class="sort">Başlık</th>
                            <th scope="col" class="sort">Tarih</th>
                            <th scope="col">Sil</th>
                            <th scope="col" class="sort">Düzenle</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>
                                    @item.ExperienceID
                                </th>
                                <td class="budget">
                                    @item.Name
                                </td>
                                <td class="budget">
                                    @item.Date
                                </td>
                                <td>
                                    <a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-sm btn-danger" id="DeleteBtn"
                                   onclick="return confirm('Silmek istediğinize emin misiniz?');">Sil</a>
                                </td>
                                <td>
                                    <a href="/Experience/EditExperience/@item.ExperienceID" class="btn btn-sm btn-success">Güncelle</a>
                                </td>

                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <div class="container">
                <a href="/Experience/AddExperience/" class="btn btn-primary">+ Deneyim Ekle</a>
            </div>
        </div>
    </div>

</div>